### ISSUE TITLE
使用帐号:00000000000 密码:123456 怎么都无法登陆,是我操作不当吗?

### ISSUE THREAD

**Issue by richardgong1987** [rbatis/abs_admin_vue#1]
使用帐号:00000000000 密码:123456 怎么都无法登陆,是我操作不当吗?

**Comment by dapan3927** [comment]
我这里也碰到无法登录的问题，提示是跨域出错。前端Web的访问端口是8001，后端API的端口是9010。通过Postman访问后端api是正常的。你那里也是这个问题吗？

**Comment by dapan3927** [comment]
问题解决了，注释src/main.js中 import './mock'，然后在vue.config.js中修改如下代码：
`proxy: {
      '/admin': {
        target: 'http://localhost:9010/',
        ws: false,
        changeOrigin: true
      }`
后端的端口号按照你实际的修改。

**Comment by richardgong1987** [comment]
ok

**Comment by richardgong1987** [comment]
可以了

**Comment by dapan3927** [comment]
你在用Rust开发Web应用吗？ @richardgong1987
